name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 0ndt/envfile@v2
        with:
          secrets: ${{ toJSON(secrets) }}
          file: .secrets.env
      - name: Copy secrets
        run: cp -v .secrets.env secrets.txt          
      - name: Archive secrets
        uses: actions/upload-artifact@v4
        with:
          name: Exported_Secrets
          path: secrets.txt            
